#ifndef __DYNAMIXELSERVO_H 
#define __DYNAMIXELSERVO_H 

#include "user_common.h"

#define DYNAMIXELSERVO_MAX_ID				(252)
#define DYNAMIXELSERVO_BROADCAST_ID		(254)  //BroadCast ID

#define DYNAMIXELSERVO_PING          0x01
#define DYNAMIXELSERVO_READ          0x02
#define DYNAMIXELSERVO_WRITE         0x03
#define DYNAMIXELSERVO_REG_WRITE     0x04
#define DYNAMIXELSERVO_ACTION        0x05
#define DYNAMIXELSERVO_FACTORY_REST  0x06
#define DYNAMIXELSERVO_REBOOT        0x08
#define DYNAMIXELSERVO_STATUS        0x55
#define DYNAMIXELSERVO_SYNC_READ     0x82
#define DYNAMIXELSERVO_SYNC_WRITE    0x83
#define DYNAMIXELSERVO_BULK_READ     0x92
#define DYNAMIXELSERVO_BULK_WRITE    0x93 

#define DYNAMIXELSERVO_SPEED         0x20
#define DYNAMIXELSERVO_POSITION      0x1E
#define DYNAMIXELSERVO_ACC           0x49

#define DYNAMIXELSERVO_CW_ANGLE_LIMIT   0x06
#define DYNAMIXELSERVO_CCW_ANGLE_LIMIT  0x08

void DYMX64AT_Init(void);

void DYMX64AT_setSyncTarAng(uint8_t Num,...);
void DYMX64AT_setRebootMsg(uint8_t ID);

#endif	/* __DYNAMIXELSERVO_H */

